default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development-pg

test:
  <<: *default
  database: db/test-pg

production:
  <<: *default
  database: db/production-pg